import type { Agent, KnowledgeSource, AgentConversation } from "@/lib/agent-types";

const HOUR_AGO = new Date(Date.now() - 3600000).toISOString();
const DAY_AGO = new Date(Date.now() - 86400000).toISOString();
const WEEK_AGO = new Date(Date.now() - 604800000).toISOString();

export const MOCK_AGENTS: Agent[] = [
  {
    id: "agt_01",
    name: "Threat Scanner",
    description: "Automated threat detection agent that monitors channels for suspicious exam-related activity and generates real-time alerts.",
    category: "security",
    status: "active",
    avatar: "TS",
    author: "ExamShield Team",
    authorAvatar: "ES",
    knowledgeCount: 12,
    conversationCount: 847,
    rating: 4.8,
    ratingCount: 124,
    isFeatured: true,
    isTrending: true,
    tags: ["threat-detection", "real-time", "monitoring"],
    createdAt: WEEK_AGO,
    lastActivity: HOUR_AGO,
    model: "gpt-4o",
  },
  {
    id: "agt_02",
    name: "Paper Forensics",
    description: "Analyzes paper watermarks, printing patterns, and physical characteristics to identify leaked examination papers.",
    category: "forensics",
    status: "active",
    avatar: "PF",
    author: "Security Lab",
    authorAvatar: "SL",
    knowledgeCount: 28,
    conversationCount: 312,
    rating: 4.6,
    ratingCount: 89,
    isFeatured: true,
    isTrending: false,
    tags: ["forensics", "watermark", "paper-analysis"],
    createdAt: WEEK_AGO,
    lastActivity: DAY_AGO,
    model: "gpt-4o",
  },
  {
    id: "agt_03",
    name: "Compliance Watchdog",
    description: "Tracks examination center compliance with security protocols and flags deviations in real-time.",
    category: "compliance",
    status: "active",
    avatar: "CW",
    author: "ExamShield Team",
    authorAvatar: "ES",
    knowledgeCount: 8,
    conversationCount: 156,
    rating: 4.3,
    ratingCount: 67,
    isFeatured: false,
    isTrending: true,
    tags: ["compliance", "protocols", "audit"],
    createdAt: DAY_AGO,
    lastActivity: HOUR_AGO,
    model: "gpt-4o-mini",
  },
  {
    id: "agt_04",
    name: "Chat Intelligence",
    description: "Processes Telegram and messaging data to extract actionable intelligence about exam security threats.",
    category: "investigation",
    status: "active",
    avatar: "CI",
    author: "Intel Division",
    authorAvatar: "ID",
    knowledgeCount: 15,
    conversationCount: 534,
    rating: 4.7,
    ratingCount: 201,
    isFeatured: true,
    isTrending: true,
    tags: ["chat-analysis", "telegram", "NLP"],
    createdAt: WEEK_AGO,
    lastActivity: HOUR_AGO,
    model: "gpt-4o",
  },
  {
    id: "agt_05",
    name: "Network Monitor",
    description: "Monitors network traffic patterns around examination centers for anomalous data transfers.",
    category: "monitoring",
    status: "paused",
    avatar: "NM",
    author: "Ops Team",
    authorAvatar: "OT",
    knowledgeCount: 6,
    conversationCount: 89,
    rating: 4.1,
    ratingCount: 34,
    isFeatured: false,
    isTrending: false,
    tags: ["network", "traffic", "anomaly"],
    createdAt: DAY_AGO,
    lastActivity: DAY_AGO,
    model: "gpt-4o-mini",
  },
  {
    id: "agt_06",
    name: "Leak Tracer",
    description: "Traces the origin and distribution path of leaked examination materials across digital channels.",
    category: "investigation",
    status: "active",
    avatar: "LT",
    author: "Security Lab",
    authorAvatar: "SL",
    knowledgeCount: 22,
    conversationCount: 198,
    rating: 4.5,
    ratingCount: 78,
    isFeatured: false,
    isTrending: true,
    tags: ["leak-analysis", "溯源", "digital-forensics"],
    createdAt: WEEK_AGO,
    lastActivity: DAY_AGO,
    model: "gpt-4o",
  },
  {
    id: "agt_07",
    name: "Report Generator",
    description: "Automatically compiles investigation findings into structured forensic reports with evidence citations.",
    category: "general",
    status: "active",
    avatar: "RG",
    author: "ExamShield Team",
    authorAvatar: "ES",
    knowledgeCount: 4,
    conversationCount: 423,
    rating: 4.4,
    ratingCount: 156,
    isFeatured: false,
    isTrending: false,
    tags: ["reports", "documentation", "automation"],
    createdAt: WEEK_AGO,
    lastActivity: HOUR_AGO,
    model: "gpt-4o-mini",
  },
  {
    id: "agt_08",
    name: "OCR Enhancement",
    description: "Enhances and validates OCR output from scanned examination documents with contextual understanding.",
    category: "forensics",
    status: "active",
    avatar: "OE",
    author: "Tech Team",
    authorAvatar: "TT",
    knowledgeCount: 9,
    conversationCount: 267,
    rating: 4.2,
    ratingCount: 91,
    isFeatured: false,
    isTrending: false,
    tags: ["OCR", "image-processing", "validation"],
    createdAt: DAY_AGO,
    lastActivity: DAY_AGO,
    model: "gpt-4o",
  },
  {
    id: "agt_09",
    name: "Risk Assessor",
    description: "Calculates and prioritizes security risks across examination centers using multi-factor analysis.",
    category: "security",
    status: "active",
    avatar: "RA",
    author: "Intel Division",
    authorAvatar: "ID",
    knowledgeCount: 11,
    conversationCount: 178,
    rating: 4.6,
    ratingCount: 102,
    isFeatured: true,
    isTrending: false,
    tags: ["risk", "prioritization", "scoring"],
    createdAt: WEEK_AGO,
    lastActivity: HOUR_AGO,
    model: "gpt-4o",
  },
  {
    id: "agt_10",
    name: "Draft Agent",
    description: "A work-in-progress agent for testing new detection patterns.",
    category: "general",
    status: "draft",
    avatar: "DA",
    author: "You",
    authorAvatar: "YU",
    knowledgeCount: 2,
    conversationCount: 0,
    rating: 0,
    ratingCount: 0,
    isFeatured: false,
    isTrending: false,
    tags: ["draft", "experimental"],
    createdAt: DAY_AGO,
    lastActivity: DAY_AGO,
    model: "gpt-4o-mini",
  },
];

export const MOCK_KNOWLEDGE_SOURCES: KnowledgeSource[] = [
  { id: "ks_01", name: "Exam Security Protocols v3", type: "document", status: "active", itemCount: 245, lastSynced: HOUR_AGO },
  { id: "ks_02", name: "NEET 2024 Case Files", type: "document", status: "active", itemCount: 1823, lastSynced: DAY_AGO },
  { id: "ks_03", name: "Threat Intelligence Feed", type: "api", status: "active", itemCount: 5670, lastSynced: HOUR_AGO },
  { id: "ks_04", name: "Center Registry DB", type: "database", status: "processing", itemCount: 4521, lastSynced: DAY_AGO },
  { id: "ks_05", name: "JEE Paper Archive", type: "document", status: "active", itemCount: 892, lastSynced: WEEK_AGO },
  { id: "ks_06", name: "Forensic Report Templates", type: "url", status: "active", itemCount: 34, lastSynced: WEEK_AGO },
];

export const MOCK_CONVERSATIONS: AgentConversation[] = [
  { id: "conv_01", agentId: "agt_01", agentName: "Threat Scanner", preview: "Analyzed 3 new suspicious messages from monitored groups...", messageCount: 12, createdAt: HOUR_AGO },
  { id: "conv_02", agentId: "agt_04", agentName: "Chat Intelligence", preview: "Extracted 5 potential lead patterns from Telegram data...", messageCount: 8, createdAt: HOUR_AGO },
  { id: "conv_03", agentId: "agt_02", agentName: "Paper Forensics", preview: "Watermark analysis complete for evidence #EV-2847...", messageCount: 15, createdAt: DAY_AGO },
  { id: "conv_04", agentId: "agt_09", agentName: "Risk Assessor", preview: "Updated risk scores for 12 examination centers...", messageCount: 6, createdAt: DAY_AGO },
];

export const CATEGORY_META: Record<string, { label: string; count: number }> = {
  security: { label: "Security", count: 2 },
  forensics: { label: "Forensics", count: 2 },
  compliance: { label: "Compliance", count: 1 },
  investigation: { label: "Investigation", count: 2 },
  monitoring: { label: "Monitoring", count: 1 },
  general: { label: "General", count: 2 },
};
