"""Hallucination detection for EXAMSHIELD AI answers.

Chat answers are generated by an LLM on top of retrieved context (tool results,
RAG chunks). LLMs occasionally state facts — counts, percentages, evidence IDs,
paper codes — that never appeared in that context. This module catches the
cheapest class of those errors without a second LLM call:

1. Split the answer into sentence-level claims.
2. Extract *checkable* tokens from each claim — numbers, percentages,
   ``EV-123``-style evidence IDs, ``NEET-2024-DEL-014``-style paper codes.
3. Flag a claim as **unsupported** when its checkable tokens are absent from
   the retrieved context.

Prose-only claims are left alone: verifying free-text semantics needs a model,
and this module is deliberately deterministic, fast, and explainable. The
request path uses ``verify_answer()`` to decide whether to trust, annotate, or
replace an answer (see chat wiring).
"""

from __future__ import annotations

import re
from collections.abc import Sequence
from dataclasses import dataclass

# Numbers (with optional decimals/thousands separators), optionally a percent.
_NUMBER_RE = re.compile(r"\b\d{1,3}(?:,\d{3})+(?:\.\d+)?%?|\b\d+(?:\.\d+)?%?")
# Evidence IDs such as EV-001 / ev-42.
_EVIDENCE_ID_RE = re.compile(r"\b(?:EV|ev)[-_]?\d{2,}\b")
# Paper/registry codes such as NEET-2024-DEL-014 or JEE-2025-MUM-7.
_PAPER_ID_RE = re.compile(r"\b[A-Z]{2,6}-\d{4}-[A-Z0-9]+(?:-[A-Z0-9]+)*\b")

_SENTENCE_SPLIT_RE = re.compile(r"(?<=[.!?])\s+|\n+")


@dataclass(frozen=True)
class ClaimCheck:
    """Verification result for one sentence-level claim."""

    claim: str
    supported: bool
    missing_evidence: tuple[str, ...] = ()

    def as_dict(self) -> dict[str, object]:
        return {
            "claim": self.claim,
            "supported": self.supported,
            "missingEvidence": list(self.missing_evidence),
        }


@dataclass(frozen=True)
class GroundingReport:
    """Aggregate verification result for a full answer."""

    checks: tuple[ClaimCheck, ...]

    @property
    def supported(self) -> tuple[ClaimCheck, ...]:
        return tuple(check for check in self.checks if check.supported)

    @property
    def unsupported(self) -> tuple[ClaimCheck, ...]:
        return tuple(check for check in self.checks if not check.supported)

    @property
    def grounded_ratio(self) -> float:
        if not self.checks:
            return 1.0
        return len(self.supported) / len(self.checks)

    @property
    def verdict(self) -> str:
        if not self.unsupported:
            return "grounded"
        if self.grounded_ratio >= 0.5:
            return "partial"
        return "ungrounded"

    def as_dict(self) -> dict[str, object]:
        return {
            "verdict": self.verdict,
            "groundedRatio": round(self.grounded_ratio, 3),
            "checks": [check.as_dict() for check in self.checks],
        }


def split_claims(answer: str) -> list[str]:
    """Split an answer into sentence-level claims."""
    parts = _SENTENCE_SPLIT_RE.split(str(answer or "").strip())
    return [part.strip() for part in parts if part and part.strip()]


def extract_checkable_tokens(text: str) -> tuple[str, ...]:
    """Return the concrete, verifiable tokens in ``text`` (IDs first, then numbers)."""
    value = str(text or "")
    tokens: list[str] = []
    seen: set[str] = set()
    for pattern in (_EVIDENCE_ID_RE, _PAPER_ID_RE, _NUMBER_RE):
        for match in pattern.finditer(value):
            token = match.group(0)
            if token.lower() not in seen:
                seen.add(token.lower())
                tokens.append(token)
    return tuple(tokens)


def _normalize(token: str) -> str:
    return token.lower().replace(",", "").replace("_", "-")


def _context_contains(context_text: str, token: str) -> bool:
    needle = _normalize(token)
    haystack = _normalize(context_text)
    if needle in haystack:
        return True
    # Percentages may be written as "12 percent" or bare "12" in the source data.
    if needle.endswith("%"):
        return needle[:-1] in haystack
    return False


def verify_claim(claim: str, context_text: str) -> ClaimCheck:
    """Check one claim's concrete tokens against the retrieved context."""
    tokens = extract_checkable_tokens(claim)
    if not tokens:
        return ClaimCheck(claim=claim, supported=True)
    missing = tuple(token for token in tokens if not _context_contains(context_text, token))
    return ClaimCheck(
        claim=claim,
        supported=not missing,
        missing_evidence=missing,
    )


def verify_answer(answer: str, contexts: Sequence[str]) -> GroundingReport:
    """Verify every claim in ``answer`` against the concatenated retrieved context."""
    context_text = "\n".join(str(chunk or "") for chunk in contexts)
    checks = tuple(verify_claim(claim, context_text) for claim in split_claims(answer))
    return GroundingReport(checks=checks)
